### ISSUE TITLE
Error typing /msg (player)

### ISSUE THREAD

**Issue by Jodexx** [zMario34/PrivateMessages#1]
I noticed a bug when you enter a player without a message, an error pops up in the console.
Here is my solution:
![image](https://user-images.githubusercontent.com/59202575/175480936-255d94e9-03d3-4df0-af55-c7e688625ce4.png)

**Comment by marioded** [comment]
> I noticed a bug when you enter a player without a message, an error pops up in the console. Here is my solution: ![image](https://user-images.githubusercontent.com/59202575/175480936-255d94e9-03d3-4df0-af55-c7e688625ce4.png)

Hey! I have already solved this problem a few days ago by testing some new features but I have not yet released the commit with the update.
